apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb-udp
  namespace: {{ .Values.jitsi.namespace }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30300
    port: 30300
    protocol: UDP
    targetPort: 30300
  selector:
    k8s-app: jitsi
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: {{ .Values.jitsi.namespace }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    k8s-app: jitsi

