apiVersion: v1
kind: Secret
metadata:
  name: jitsi-config
data:
  JICOFO_AUTH_PASSWORD: {{ .Values.jitsi.secrets.JICOFO_AUTH_PASSWORD | b64enc }}
  JICOFO_COMPONENT_SECRET: {{ .Values.jitsi.secrets.JICOFO_COMPONENT_SECRET | b64enc }}
  JVB_AUTH_PASSWORD: {{ .Values.jitsi.secrets.JVB_AUTH_PASSWORD | b64enc }}
