apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jitsi-privileged
  namespace: {{ .Values.jitsi.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jitsi-privileged
subjects:
- kind: ServiceAccount
  name: jitsi
  namespace: jitsi

